apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx.minikube.local
spec:
  rules:
  - host: nginx.minikube.local
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
