#!/usr/bin/env bash

# Copyright (c) 2017 Kazuki Suda <kazuki.suda@gmail.com>
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

set -e

MINIKUBE_INGRESS_DNS_DOMAIN=${MINIKUBE_INGRESS_DNS_DOMAIN:-minikube.dev}

minikube "$@"

if [[ "$1" == "start" ]]; then
  ip="$(minikube ip)"
  echo "The IP address of running a cluster: ${ip}"

  config="$(cat <<EOL
bind-interfaces
listen-address=127.0.0.1
address=/${MINIKUBE_INGRESS_DNS_DOMAIN}/${ip}
EOL
)"
  config_file="/usr/local/etc/dnsmasq.conf"

  if [[ "$config" != "$(cat $config_file 2>/dev/null)" ]]; then
    echo "Configuring dnsmasq for ${MINIKUBE_INGRESS_DNS_DOMAIN}..."
    echo "$config" > "$config_file"

    echo "Restarting dnsmasq..."
    sudo brew services restart dnsmasq
  fi

  if [[ ! -f "/etc/resolver/${MINIKUBE_INGRESS_DNS_DOMAIN}" ]]; then
    sudo mkdir -p /etc/resolver/
    sudo bash -c "echo 'nameserver 127.0.0.1' > /etc/resolver/${MINIKUBE_INGRESS_DNS_DOMAIN}"
  fi

  dig +noall +answer "${MINIKUBE_INGRESS_DNS_DOMAIN}"
fi
# vim: ft=sh ts=2 sts=2 sw=2
