#!/usr/bin/env bash

# minikube-ingress-dns-ubuntu16
# Copyright (c) 2017 Kazuki Suda <kazuki.suda@gmail.com>
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

set -e
set -o pipefail

command minikube $@

[[ -n "$DEBUG" ]] && set -x

[[ "$1" != "start" ]] && exit

source $(dirname $0)/common.sh

# The file path of dnsmasq.conf
dnsmasq_config_file=/etc/NetworkManager/dnsmasq.d/minikube.conf
write_to_dnsmasq_config_file() {
  local tmpfile="$(mktemp)"

  cat > $tmpfile
  exe sudo mv $tmpfile $dnsmasq_config_file
}

# The way of restarting dnsmasq in this environment
restart_dnsmasq() {
  sudo systemctl restart NetworkManager
}

# Setup dnsmasq for ingress lb in minikube
minikube_ingress_dns
# vim: ft=sh ts=2 sts=2 sw=2
